### ISSUE TITLE
Industriasl cogwheels crash game

### ISSUE THREAD

**Issue by chelovek124** [DrMango14/Create-Design-n-Decor#11]
[latest.log](https://github.com/DrMango14/Create-Design-n-Decor/files/14220836/latest.log)

When i place industrial cogwheel it crash game

**Comment by YassaaaTU** [comment]
I have the same issue.
Only tested with industrial cogwheel.
There might be other items/blocks that crash the game.

Minecraft: 1.20.1
Forge: 47.2.20

**Comment by criscanz** [comment]
I have the same problem, and now the chunks on the server are crashing peoples games.

**Comment by GeradesoLukas** [comment]
The large industrial cogwheels seem to be the problem

**Comment by FreudianFondue** [comment]
Having the same issue here

**Comment by Mecanix-Creations** [comment]
Idk why large industrial cogs doing this

**Comment by LopyLuna** [comment]
fixed
