### ISSUE TITLE
Industrial Gear crash my game and corupte my world 

### ISSUE THREAD

**Issue by TheFireSkorpion** [DrMango14/Create-Design-n-Decor#15]

**Comment by Elam-Monnot** [comment]
I had the same issue, for me it occured when using industrial block on a large cogwheel. I had to remove the mod and reload the game to make it disappear. Else, every time I launched the world I crashed immediately.
I am using embeddium, but the game crashed even without it.

**Comment by Tollainmear** [comment]
Same problem here.

**Comment by KatTheLootgoblin** [comment]
Same problem here, specifically with the industrial cogwheel.
Recommend not updating the mod until this is adressed.

**Comment by LopyLuna** [comment]
fixed
