### ISSUE TITLE
[Suggestion] Compact Fluid Tanks should keep their fluid contents when broken.

### ISSUE THREAD

**Issue by goldrat1** [DrMango14/Create-Design-n-Decor#26]
Self-explanatory. Compact Fluid Tanks and Iron Compact Fluid Tanks should have their fluid contents kept when broken, allowing you to transport fluids in a cool and convenient way, and gives them a different use than just being a small non-expandable fluid tank.

**Comment by LopyLuna** [comment]
only works when its full
