### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by qwek1** [DrMango14/Create-Design-n-Decor#3]
Once every few times when launching the game, the mod will fail to load.
[latest (31).log](https://github.com/DrMango14/Create-Design-n-Decor/files/13318852/latest.31.log)
[crash-2023-11-10_01.07.38-fml.txt](https://github.com/DrMango14/Create-Design-n-Decor/files/13318853/crash-2023-11-10_01.07.38-fml.txt)

**Comment by LopyLuna** [comment]
mod conflict likely

**Comment by qwek1** [comment]
Is there any way to figure which mod it is without doing a binary search? Or would that be the only option. Would I it also be another create addon conflicting with it?

**Comment by zaeonNineZero** [comment]
Was having the same mod loading error, but it seems to have been fixed in the 0.2a update.
