### ISSUE TITLE
Copper floodlight does not have a crafting recipe.

### ISSUE THREAD

**Issue by DaPuffer** [DrMango14/Create-Design-n-Decor#6]
It just does not.

**Comment by FirewallDaProtogen** [comment]
im having the same issue! it really sucks because i used it alot in my schematics :(

**Comment by FirewallDaProtogen** [comment]
i just created a pull request which fixes it. now i just need to get it approved

**Comment by FirewallDaProtogen** [comment]
wdym not planned? was it fixed or are you planning on adding my pull request thingy?
